// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.21.5
// source: tss.proto

package tss

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DKGRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DKGRequest) Reset() {
	*x = DKGRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tss_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DKGRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DKGRequest) ProtoMessage() {}

func (x *DKGRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tss_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DKGRequest.ProtoReflect.Descriptor instead.
func (*DKGRequest) Descriptor() ([]byte, []int) {
	return file_tss_proto_rawDescGZIP(), []int{0}
}

type SignRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hash    string `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	Pubkey  string `protobuf:"bytes,2,opt,name=pubkey,proto3" json:"pubkey,omitempty"`
	Message string `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *SignRequest) Reset() {
	*x = SignRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tss_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SignRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignRequest) ProtoMessage() {}

func (x *SignRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tss_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignRequest.ProtoReflect.Descriptor instead.
func (*SignRequest) Descriptor() ([]byte, []int) {
	return file_tss_proto_rawDescGZIP(), []int{1}
}

func (x *SignRequest) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *SignRequest) GetPubkey() string {
	if x != nil {
		return x.Pubkey
	}
	return ""
}

func (x *SignRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ReshareRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hash   string `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	Pubkey string `protobuf:"bytes,2,opt,name=pubkey,proto3" json:"pubkey,omitempty"`
}

func (x *ReshareRequest) Reset() {
	*x = ReshareRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tss_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReshareRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReshareRequest) ProtoMessage() {}

func (x *ReshareRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tss_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReshareRequest.ProtoReflect.Descriptor instead.
func (*ReshareRequest) Descriptor() ([]byte, []int) {
	return file_tss_proto_rawDescGZIP(), []int{2}
}

func (x *ReshareRequest) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *ReshareRequest) GetPubkey() string {
	if x != nil {
		return x.Pubkey
	}
	return ""
}

type RVSignatureReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	R    string `protobuf:"bytes,1,opt,name=r,proto3" json:"r,omitempty"`
	S    string `protobuf:"bytes,2,opt,name=s,proto3" json:"s,omitempty"`
	Hash string `protobuf:"bytes,3,opt,name=hash,proto3" json:"hash,omitempty"`
}

func (x *RVSignatureReply) Reset() {
	*x = RVSignatureReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tss_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RVSignatureReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RVSignatureReply) ProtoMessage() {}

func (x *RVSignatureReply) ProtoReflect() protoreflect.Message {
	mi := &file_tss_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RVSignatureReply.ProtoReflect.Descriptor instead.
func (*RVSignatureReply) Descriptor() ([]byte, []int) {
	return file_tss_proto_rawDescGZIP(), []int{3}
}

func (x *RVSignatureReply) GetR() string {
	if x != nil {
		return x.R
	}
	return ""
}

func (x *RVSignatureReply) GetS() string {
	if x != nil {
		return x.S
	}
	return ""
}

func (x *RVSignatureReply) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

type DkgReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X       string `protobuf:"bytes,1,opt,name=x,proto3" json:"x,omitempty"`
	Y       string `protobuf:"bytes,2,opt,name=y,proto3" json:"y,omitempty"`
	Pubkey  string `protobuf:"bytes,3,opt,name=pubkey,proto3" json:"pubkey,omitempty"`
	Address string `protobuf:"bytes,4,opt,name=address,proto3" json:"address,omitempty"`
}

func (x *DkgReply) Reset() {
	*x = DkgReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tss_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DkgReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DkgReply) ProtoMessage() {}

func (x *DkgReply) ProtoReflect() protoreflect.Message {
	mi := &file_tss_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DkgReply.ProtoReflect.Descriptor instead.
func (*DkgReply) Descriptor() ([]byte, []int) {
	return file_tss_proto_rawDescGZIP(), []int{4}
}

func (x *DkgReply) GetX() string {
	if x != nil {
		return x.X
	}
	return ""
}

func (x *DkgReply) GetY() string {
	if x != nil {
		return x.Y
	}
	return ""
}

func (x *DkgReply) GetPubkey() string {
	if x != nil {
		return x.Pubkey
	}
	return ""
}

func (x *DkgReply) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type CheckSignatureByPubkeyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Pubkey  string `protobuf:"bytes,2,opt,name=pubkey,proto3" json:"pubkey,omitempty"`
}

func (x *CheckSignatureByPubkeyRequest) Reset() {
	*x = CheckSignatureByPubkeyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tss_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckSignatureByPubkeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckSignatureByPubkeyRequest) ProtoMessage() {}

func (x *CheckSignatureByPubkeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tss_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckSignatureByPubkeyRequest.ProtoReflect.Descriptor instead.
func (*CheckSignatureByPubkeyRequest) Descriptor() ([]byte, []int) {
	return file_tss_proto_rawDescGZIP(), []int{5}
}

func (x *CheckSignatureByPubkeyRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CheckSignatureByPubkeyRequest) GetPubkey() string {
	if x != nil {
		return x.Pubkey
	}
	return ""
}

type ServiceReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ServiceReply) Reset() {
	*x = ServiceReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tss_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServiceReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceReply) ProtoMessage() {}

func (x *ServiceReply) ProtoReflect() protoreflect.Message {
	mi := &file_tss_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceReply.ProtoReflect.Descriptor instead.
func (*ServiceReply) Descriptor() ([]byte, []int) {
	return file_tss_proto_rawDescGZIP(), []int{6}
}

var File_tss_proto protoreflect.FileDescriptor

var file_tss_proto_rawDesc = []byte{
	0x0a, 0x09, 0x74, 0x73, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x74, 0x73, 0x73,
	0x22, 0x0c, 0x0a, 0x0a, 0x44, 0x4b, 0x47, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x53,
	0x0a, 0x0b, 0x53, 0x69, 0x67, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a,
	0x04, 0x68, 0x61, 0x73, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x68, 0x61, 0x73,
	0x68, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x75, 0x62, 0x6b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x70, 0x75, 0x62, 0x6b, 0x65, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x22, 0x3c, 0x0a, 0x0e, 0x52, 0x65, 0x73, 0x68, 0x61, 0x72, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x61, 0x73, 0x68, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x68, 0x61, 0x73, 0x68, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x75, 0x62,
	0x6b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x75, 0x62, 0x6b, 0x65,
	0x79, 0x22, 0x42, 0x0a, 0x10, 0x52, 0x56, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x0c, 0x0a, 0x01, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x01, 0x72, 0x12, 0x0c, 0x0a, 0x01, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x01,
	0x73, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x61, 0x73, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x68, 0x61, 0x73, 0x68, 0x22, 0x58, 0x0a, 0x08, 0x44, 0x6b, 0x67, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x12, 0x0c, 0x0a, 0x01, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x01, 0x78, 0x12,
	0x0c, 0x0a, 0x01, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x01, 0x79, 0x12, 0x16, 0x0a,
	0x06, 0x70, 0x75, 0x62, 0x6b, 0x65, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70,
	0x75, 0x62, 0x6b, 0x65, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x22,
	0x51, 0x0a, 0x1d, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72,
	0x65, 0x42, 0x79, 0x50, 0x75, 0x62, 0x6b, 0x65, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x75,
	0x62, 0x6b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x75, 0x62, 0x6b,
	0x65, 0x79, 0x22, 0x0e, 0x0a, 0x0c, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x32, 0xac, 0x01, 0x0a, 0x0a, 0x54, 0x73, 0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x12, 0x38, 0x0a, 0x0b, 0x53, 0x69, 0x67, 0x6e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x12, 0x10, 0x2e, 0x74, 0x73, 0x73, 0x2e, 0x53, 0x69, 0x67, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x15, 0x2e, 0x74, 0x73, 0x73, 0x2e, 0x52, 0x56, 0x53, 0x69, 0x67, 0x6e, 0x61,
	0x74, 0x75, 0x72, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x2f, 0x0a, 0x0b, 0x52,
	0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x44, 0x4b, 0x47, 0x12, 0x0f, 0x2e, 0x74, 0x73, 0x73,
	0x2e, 0x44, 0x4b, 0x47, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0d, 0x2e, 0x74, 0x73,
	0x73, 0x2e, 0x44, 0x6b, 0x67, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x33, 0x0a, 0x07,
	0x52, 0x65, 0x73, 0x68, 0x61, 0x72, 0x65, 0x12, 0x13, 0x2e, 0x74, 0x73, 0x73, 0x2e, 0x52, 0x65,
	0x73, 0x68, 0x61, 0x72, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x11, 0x2e, 0x74,
	0x73, 0x73, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22,
	0x00, 0x42, 0x06, 0x5a, 0x04, 0x74, 0x73, 0x73, 0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_tss_proto_rawDescOnce sync.Once
	file_tss_proto_rawDescData = file_tss_proto_rawDesc
)

func file_tss_proto_rawDescGZIP() []byte {
	file_tss_proto_rawDescOnce.Do(func() {
		file_tss_proto_rawDescData = protoimpl.X.CompressGZIP(file_tss_proto_rawDescData)
	})
	return file_tss_proto_rawDescData
}

var file_tss_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_tss_proto_goTypes = []interface{}{
	(*DKGRequest)(nil),                    // 0: tss.DKGRequest
	(*SignRequest)(nil),                   // 1: tss.SignRequest
	(*ReshareRequest)(nil),                // 2: tss.ReshareRequest
	(*RVSignatureReply)(nil),              // 3: tss.RVSignatureReply
	(*DkgReply)(nil),                      // 4: tss.DkgReply
	(*CheckSignatureByPubkeyRequest)(nil), // 5: tss.CheckSignatureByPubkeyRequest
	(*ServiceReply)(nil),                  // 6: tss.ServiceReply
}
var file_tss_proto_depIdxs = []int32{
	1, // 0: tss.TssService.SignMessage:input_type -> tss.SignRequest
	0, // 1: tss.TssService.RegisterDKG:input_type -> tss.DKGRequest
	2, // 2: tss.TssService.Reshare:input_type -> tss.ReshareRequest
	3, // 3: tss.TssService.SignMessage:output_type -> tss.RVSignatureReply
	4, // 4: tss.TssService.RegisterDKG:output_type -> tss.DkgReply
	6, // 5: tss.TssService.Reshare:output_type -> tss.ServiceReply
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_tss_proto_init() }
func file_tss_proto_init() {
	if File_tss_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_tss_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DKGRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tss_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SignRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tss_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReshareRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tss_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RVSignatureReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tss_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DkgReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tss_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckSignatureByPubkeyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tss_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServiceReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_tss_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tss_proto_goTypes,
		DependencyIndexes: file_tss_proto_depIdxs,
		MessageInfos:      file_tss_proto_msgTypes,
	}.Build()
	File_tss_proto = out.File
	file_tss_proto_rawDesc = nil
	file_tss_proto_goTypes = nil
	file_tss_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// TssServiceClient is the client API for TssService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TssServiceClient interface {
	SignMessage(ctx context.Context, in *SignRequest, opts ...grpc.CallOption) (*RVSignatureReply, error)
	RegisterDKG(ctx context.Context, in *DKGRequest, opts ...grpc.CallOption) (*DkgReply, error)
	Reshare(ctx context.Context, in *ReshareRequest, opts ...grpc.CallOption) (*ServiceReply, error)
}

type tssServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTssServiceClient(cc grpc.ClientConnInterface) TssServiceClient {
	return &tssServiceClient{cc}
}

func (c *tssServiceClient) SignMessage(ctx context.Context, in *SignRequest, opts ...grpc.CallOption) (*RVSignatureReply, error) {
	out := new(RVSignatureReply)
	err := c.cc.Invoke(ctx, "/tss.TssService/SignMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tssServiceClient) RegisterDKG(ctx context.Context, in *DKGRequest, opts ...grpc.CallOption) (*DkgReply, error) {
	out := new(DkgReply)
	err := c.cc.Invoke(ctx, "/tss.TssService/RegisterDKG", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tssServiceClient) Reshare(ctx context.Context, in *ReshareRequest, opts ...grpc.CallOption) (*ServiceReply, error) {
	out := new(ServiceReply)
	err := c.cc.Invoke(ctx, "/tss.TssService/Reshare", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TssServiceServer is the server API for TssService service.
type TssServiceServer interface {
	SignMessage(context.Context, *SignRequest) (*RVSignatureReply, error)
	RegisterDKG(context.Context, *DKGRequest) (*DkgReply, error)
	Reshare(context.Context, *ReshareRequest) (*ServiceReply, error)
}

// UnimplementedTssServiceServer can be embedded to have forward compatible implementations.
type UnimplementedTssServiceServer struct {
}

func (*UnimplementedTssServiceServer) SignMessage(context.Context, *SignRequest) (*RVSignatureReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SignMessage not implemented")
}
func (*UnimplementedTssServiceServer) RegisterDKG(context.Context, *DKGRequest) (*DkgReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterDKG not implemented")
}
func (*UnimplementedTssServiceServer) Reshare(context.Context, *ReshareRequest) (*ServiceReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Reshare not implemented")
}

func RegisterTssServiceServer(s *grpc.Server, srv TssServiceServer) {
	s.RegisterService(&_TssService_serviceDesc, srv)
}

func _TssService_SignMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TssServiceServer).SignMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tss.TssService/SignMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TssServiceServer).SignMessage(ctx, req.(*SignRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TssService_RegisterDKG_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DKGRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TssServiceServer).RegisterDKG(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tss.TssService/RegisterDKG",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TssServiceServer).RegisterDKG(ctx, req.(*DKGRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TssService_Reshare_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReshareRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TssServiceServer).Reshare(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tss.TssService/Reshare",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TssServiceServer).Reshare(ctx, req.(*ReshareRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _TssService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "tss.TssService",
	HandlerType: (*TssServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SignMessage",
			Handler:    _TssService_SignMessage_Handler,
		},
		{
			MethodName: "RegisterDKG",
			Handler:    _TssService_RegisterDKG_Handler,
		},
		{
			MethodName: "Reshare",
			Handler:    _TssService_Reshare_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "tss.proto",
}
